### ISSUE TITLE
Type information?

### ISSUE THREAD

**Issue by pdf** [wndhydrnt/go-signature-statusbar#10]
Is it possible to add type info for variables?

**Comment by wndhydrnt** [comment]
Sadly, this is currently not possible. This module uses [gocode](https://github.com/nsf/gocode) under the hood and gocode does not provide meaningful information on the type of a variable.

**Comment by pdf** [comment]
@wndhydrnt pretty certain it does:

```
2016/08/20 03:55:29 -------------------------------------------------------
2016/08/20 03:55:29 Found "fmt" at "/usr/local/go/pkg/linux_amd64/fmt.a"
2016/08/20 03:55:29 Offset: 0
2016/08/20 03:55:29 Number of candidates found: 3
2016/08/20 03:55:29 Candidates are:
2016/08/20 03:55:29   func main()
2016/08/20 03:55:29   package fmt 
2016/08/20 03:55:29   var intVar int
2016/08/20 03:55:29 =======================================================
2016/08/20 03:55:29 Go project path: .
2016/08/20 03:55:29 Got autocompletion request for '/tmp/main.go'
2016/08/20 03:55:29 Cursor at: 62
2016/08/20 03:55:29 -------------------------------------------------------
package main

import "fmt"

func main() {
        var intVar int

        in#tVar = 1

        fmt.Println(intVar)
}
2016/08/20 03:55:29 -------------------------------------------------------
2016/08/20 03:55:29 Found "fmt" at "/usr/local/go/pkg/linux_amd64/fmt.a"
2016/08/20 03:55:29 Offset: 2
2016/08/20 03:55:29 Number of candidates found: 1
2016/08/20 03:55:29 Candidates are:
2016/08/20 03:55:29   var intVar int
2016/08/20 03:55:29 =======================================================
2016/08/20 03:55:31 Go project path: .
2016/08/20 03:55:31 Got autocompletion request for '/tmp/main.go'
2016/08/20 03:55:31 Cursor at: 62
2016/08/20 03:55:31 -------------------------------------------------------
```

**Comment by wndhydrnt** [comment]
Looks like it does not work if the variable is defined using `:=`:

```
# hello.go
package main

import "fmt"

func test() {
        var faa string

        faa = "faa"
        foo := "foo"

        fmt.Println(foo)
}
```

```
$ gocode -f json -in="./hello.go" autocomplete hello.go 80
[0, [{"class": "func", "name": "test", "type": "func()"}, {"class": "package", "name": "fmt", "type": ""}, {"class": "var", "name": "faa", "type": "string"}, {"class": "var", "name": "foo", "type": ""}]]
```

No type information for `foo` here, but for `faa`.

Also, the code in this package tries to figure out whether the cursor is currently focusing a function and that makes widening the scope of this package quite hard. It would be great if a command-line tool would exist that takes a file and an offset and returns the type information. [guru](https://godoc.org/golang.org/x/tools/cmd/guru) can do this but it was pretty slow when the project is relatively large the last time I checked. I'm keeping an eye on it, though.

**Comment by pdf** [comment]
> No type information for foo here, but for faa.

Something is better than nothing?  The only case I can see that it doesn't work for is initialising a var with an inferred type (because that's difficult, since Go uses some magic here) - it works for declared vars, consts, struct fields, values returned from function calls.

>  It would be great if a command-line tool would exist that takes a file and an offset and returns the type information

That's exactly what gocode does, no?

```
autocomplete [<path>] <offset>     main autocompletion command
```
