### ISSUE TITLE
Font size is too small

### ISSUE THREAD

**Issue by ghost** [wndhydrnt/go-signature-statusbar#11]
If possible please add an option for setting default font size, this will be very useful.

**Comment by wndhydrnt** [comment]
@dineshbhosale 
Did some research on this by searching for "status bar" on atom.io and checking how other package maintainers have solved the problem. I only looked at packages that had more than 1000 downloads. Here's what I found:
- [status-bar](https://atom.io/packages/status-bar) - Does not provide that option
- [time-status](https://atom.io/packages/time-status) - Does not provide that option
- [indentation-indicator](https://atom.io/packages/indentation-indicator) - A section in the README refers to CSS classes one can use to change the appearance in the status bar
- [ctags-status](https://atom.io/packages/ctags-status) - Does not provide that option

So judging from this, I suggest you change the font size by customizing your stylesheet as [described in the Atom Flight Manual](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks).

I'm using this:

```
.status-bar {
  font-size: 8px;
}
```

If you just want to change the font size of go-signature-statusbar, you can do that too:

```
.go-signature-statusbar {
  font-size: 20px;
}
```
