### ISSUE TITLE
Method signature being truncated

### ISSUE THREAD

**Issue by tbillington** [wndhydrnt/go-signature-statusbar#4]
It seems that the method signature is truncated after it reaches a certain length. I had a quick look at the code and couldn't see this happening intentionally so it may be coming from autocomplete.

![truncated signature screenshot](http://i.imgur.com/arWiTLb.png)

**Comment by wndhydrnt** [comment]
I noticed that too. The [statusbar package](https://github.com/atom/status-bar/blob/master/styles/status-bar.less#L59) is setting the limit.
It should be possible to override the setting, but I would rather not do that as it could be surprising for users.
An alternative could be to display the full signature in a tooltip when hovering over the text, just like the git package does when hovering over the name of the current branch.

What do you think @tbillington?

**Comment by gwilym** [comment]
A personal workaround at least is to add this to your stylesheet (Preferences > Stylesheet...):

```
status-bar .go-signature-statusbar {
  max-width: none;
}
```

![image](https://cloud.githubusercontent.com/assets/270947/15810819/f1946f7e-2b91-11e6-9639-fd9053a2bd4f.png)

Thank you for this package.

**Comment by tbillington** [comment]
@wndhydrnt That seems like one possible solution. Perhaps it could be a setting of the package to override the default length, as suggested by @gwilym ?

**Comment by wndhydrnt** [comment]
Thanks for the input. If people are already working around this by altering the CSS, I think it's fine to provide it as a setting. I'll look into this.

**Comment by tbillington** [comment]
Awesome, got the update, looks good! 👍

**Comment by eduncan911** [comment]
I was coming here to open an issue for this, as I saw an update available and thought, "yeah, I need to open an issue about that truncating."

and yet, here's the first and configuration param!  BAM!  

Thank you!
